spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: Yamaoki
    password: 26082000
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres